name: tests

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.12' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          pip install --upgrade pip  
          pip install --upgrade build    
          pip install -e .[test]
          pip install -e .[i18n]
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
      - name: Run unit-tests
        run: pytest -v -m "not network_dependent"